### ISSUE TITLE
Cannot read property 'setNewState' of undefined

### ISSUE THREAD

**Issue by kavehcito** [KBLNY/react-native-message-bar#1]
Hello -

Thanks for this.  I am surely missing something basic, but when I try to display an alert, the showCurrentAlert function of MessageBarManager barfs @ line 47 - "Cannot read property 'setNewState' of undefined. 

My project is set up with a redux store and a router.  When I just drop your example code into my project, it works fine. 

Kaveh

**Comment by KBLNY** [comment]
Hi,
Can you please paste the code that call MessageBarManager.showCurrentAlert({...}), notably explaining how you use this component in your architecture?
Which version do you use? 

Can you also please check you implemented the following step:
1. Add a `<MessageBar ref="alert" />` to your top parent view/component. (Children will use that one)
2. Register and unregister the alert in, respectively, `componentDidMount` and `componentWillUnmount`
3. Call `MessageBarManager.showCurrentAlert({...})` with the right properties

Thanks,

Kevin

**Comment by kavehcito** [comment]
Hello -
Thanks for helping. 

I figured the problem out, totally on my side.  My render function briefly branches and returns a view while the saved state is loading, and I did not have the MessageBar in that first returned view, so this.refs.alert was null when the component mounted.  

Thanks,
Kaveh

**Comment by KBLNY** [comment]
Hi,
I'm glad you solved your problem.
However, I'm open to any suggestion to improve this component. Feel free to submit a PR :)
Thanks
Kevin
