### ISSUE TITLE
Upgrade to react-native 0.25

### ISSUE THREAD

**Issue by johnjerrico** [KBLNY/react-native-message-bar#12]
Hi, 
there are some deprecation notice from react-native please see broken changes on 
the following link https://github.com/facebook/react-native/releases/tag/v0.25.1

ps :  @sibeliusseraphini provides tool for update to 0.25
https://github.com/sibeliusseraphini/codemod-RN24-to-RN25

**Comment by KBLNY** [comment]
Hi, Thanks for this.
Updated in v1.6.0
