### ISSUE TITLE
titleStyle and MessageStyle is not applied when stylesheetSuccess is used

### ISSUE THREAD

**Issue by gang89** [KBLNY/react-native-message-bar#44]
Hi,
Am facing an issue where alertType is success and when there is stylesheetSuccess applied, titleStyle and MessageStyle (where color: 'white') is not applied. Any advise?

`showInAppAlert(title, message, callbackFunction){
    MessageBarManager.showAlert({
      title : title,
      message: message,
      alertType: 'success',
      avatar: `<${this.state.userIcon.uri}>`,
      duration : 20000,
      viewTopOffset : 0,
      viewTopInset : 20,
      onTapped:()=>{callbackFunction()},
      stylesheetSuccess : { backgroundColor: '#32A54A', fontSize: 16},
      titleStyle : {
        color : 'white',
        fontSize : 16,
        fontFamily : Fonts.type.bold,
        fontWeight : 'bold',
        marginBottom : 2,
      },
      messageStyle : {
        color : 'white',
        fontFamily : Fonts.type.base,
        fontSize : 14,
        marginBottom : 2
      },
      avatarStyle: { height: 40, width: 40, borderRadius: 20 },
      messageNumberOfLines : 5,
    });
  }`

**Comment by Volekss** [comment]
So, what was the solution?
