### ISSUE TITLE
Shows extra blue(info) bar when any message slides up.

### ISSUE THREAD

**Issue by zsajjad** [KBLNY/react-native-message-bar#6]
`_showAlert(_message, _alertType = 'error') {
    MessageBarManager.showAlert({
      message:  _message,
      alertType: _alertType
    });
  }`

when duration ends small blue bar appears on top after the error bar exit animation ends

**Comment by KBLNY** [comment]
Ok, thanks for your feedback.
I'm investigating and I will keep you in touch.
Btw, which versions of RN and message-bar do you use?

**Comment by emiraydin** [comment]
@zsajjad This happened for me when the MessageBar component wasn't a child of the top level component. Could you please confirm MessageBar is a child of the top component?

**Comment by KBLNY** [comment]
Your `MessageBar`component should be added to your main top component. Let's named it A. You should register for the `MessageBar` in this component A.
You can call for displaying the `MessageBar` alert from A or one of its children components, that's the reason why you should register it.
When the component A is unmount you should release the registration of the `MessageBar` and do the same for another main top component.

Btw, I'm working on a simpler way to call the alert like `Alert.alert("my message)` working without registration and from any top or child component

**Comment by zsajjad** [comment]
@KBLNY using RN v0.23 & react-native-message-bar v1.4.0!

**Comment by KBLNY** [comment]
Please update to v1.4.2

**Comment by shukerullah** [comment]
@KBLNY thanks, blue bar is not appearing after updating to v.14.2

**Comment by antonzy** [comment]
I also got the blue bar, using v1.5.2
Happens when I do a scene transition (like close an open modal) while the message is shown.

**Comment by KBLNY** [comment]
Hi,
What module do you use for Modal?
Can you please give me a piece of code regarding your transition?
Thanks, I'll keep digging that

**Comment by antonzy** [comment]
@KBLNY I'm using [https://github.com/aksonov/react-native-router-flux](https://github.com/aksonov/react-native-router-flux).

**Comment by antonzy** [comment]
@KBLNY I wish to add that it appears over the status bar, even if alert position is 'bottom'

**Comment by marcosinigaglia** [comment]
Any news on this bug?
